import {useEffect,useState} from "react";
import {useAuth} from "../../context/AuthContext"; import {useToast} from "../../context/ToastContext"; import {labApi} from "../../api/hmsModules";
import {PageHeader,FullPageLoader} from "../../components/Atoms";
const STATUSES=["REQUESTED","IN_PROGRESS","COMPLETED","CANCELLED"];
export default function LabTests(){
 const {user}=useAuth(); const toast=useToast(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true);
 const [f,setF]=useState({patientId:user.role==="PATIENT"?String(user.profileId):"",doctorId:user.role==="DOCTOR"?String(user.profileId):"",medicalRecordId:"",testName:""});
 const load=async()=>{setLoading(true);try{setRows(user.role==="PATIENT"?await labApi.patient(user.profileId):await labApi.all())}catch(e){toast.error(e.friendlyMessage||"Could not load lab tests")}finally{setLoading(false)}};
 useEffect(()=>{load()},[user]);
 const create=async e=>{e.preventDefault();try{await labApi.create({...f,patientId:Number(f.patientId),doctorId:f.doctorId?Number(f.doctorId):null,medicalRecordId:f.medicalRecordId?Number(f.medicalRecordId):null});toast.success("Lab test requested");setF({...f,testName:"",medicalRecordId:""});load()}catch(e){toast.error(e.friendlyMessage||"Could not request lab test")}};
 const result=async row=>{const value=window.prompt("Enter result value",row.resultValue||"");if(value===null)return;try{await labApi.result(row.id,{resultValue:value});toast.success("Result saved");load()}catch(e){toast.error(e.friendlyMessage||"Could not save result")}};
 const status=async(row,s)=>{try{await labApi.status(row.id,s);toast.success("Lab status updated");load()}catch(e){toast.error(e.friendlyMessage||"Could not update status")}};
 if(loading)return <FullPageLoader label="Loading lab tests…"/>;
 return <div><PageHeader eyebrow="Laboratory" title="Lab Tests" subtitle="Request tests, track status and enter results according to your role."/>
 {["DOCTOR","ADMIN"].includes(user.role)&&<form onSubmit={create} className="card p-5 mb-6 grid md:grid-cols-4 gap-3"><input className="input" placeholder="Patient ID" value={f.patientId} onChange={e=>setF({...f,patientId:e.target.value})} required/><input className="input" placeholder="Doctor ID" value={f.doctorId} onChange={e=>setF({...f,doctorId:e.target.value})}/><input className="input" placeholder="Medical Record ID" value={f.medicalRecordId} onChange={e=>setF({...f,medicalRecordId:e.target.value})}/><input className="input" placeholder="Test name" value={f.testName} onChange={e=>setF({...f,testName:e.target.value})} required/><button className="btn-primary md:col-span-4">Request test</button></form>}
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="th">ID</th><th className="th">Patient</th><th className="th">Test</th><th className="th">Status</th><th className="th">Result</th><th className="th">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-line"><td className="td">{r.id}</td><td className="td">{r.patientName||r.patientId}</td><td className="td">{r.testName}</td><td className="td"><span className="badge bg-ink-100">{r.status}</span></td><td className="td">{r.resultValue||"Pending"}</td><td className="td"><div className="flex gap-2 flex-wrap">{["LAB_TECH","ADMIN"].includes(user.role)&&<><button className="btn-outline px-2 py-1 text-xs" onClick={()=>result(r)}>Enter result</button><select className="input !w-auto !py-1" value={r.status} onChange={e=>status(r,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></>}</div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-sm text-ink-400">No lab tests found.</p>}</div></div>;
}