spring.application.name=Hospital

# Aiven Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Admin
admin.name=${ADMIN_NAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
