import {useEffect,useState} from "react";
import {ipdApi} from "../../api/hmsModules"; import {useAuth} from "../../context/AuthContext"; import {useToast} from "../../context/ToastContext"; import {PageHeader,FullPageLoader,StatCard} from "../../components/Atoms";
export default function IPD(){
 const {user}=useAuth(); const toast=useToast(); const [beds,setBeds]=useState([]); const [admissions,setAdmissions]=useState([]); const [loading,setLoading]=useState(true); const [bf,setBf]=useState({wardName:"General",bedNumber:""}); const [af,setAf]=useState({patientId:"",bedId:""});
 const canBed=["ADMIN","RECEPTIONIST"].includes(user.role), canDeleteBed=user.role==="ADMIN", canAdmit=["ADMIN","RECEPTIONIST","DOCTOR"].includes(user.role), canDischarge=["ADMIN","RECEPTIONIST","DOCTOR","NURSE"].includes(user.role);
 const load=async()=>{setLoading(true);try{if(user.role==="PATIENT"){setBeds([]);setAdmissions(await ipdApi.patientAdmissions(user.profileId)||[])}else{const [b,a]=await Promise.all([ipdApi.beds(),ipdApi.activeAdmissions()]);setBeds(b||[]);setAdmissions(a||[])}}catch(e){toast.error(e.friendlyMessage||"Could not load IPD")}finally{setLoading(false)}};useEffect(()=>{load()},[user]);
 const addBed=async e=>{e.preventDefault();try{await ipdApi.createBed(bf);toast.success("Bed created");setBf({wardName:"General",bedNumber:""});load()}catch(e){toast.error(e.friendlyMessage||"Could not create bed")}};
 const admit=async e=>{e.preventDefault();try{await ipdApi.admit({patientId:Number(af.patientId),bedId:Number(af.bedId)});toast.success("Patient admitted to bed");setAf({patientId:"",bedId:""});load()}catch(e){toast.error(e.friendlyMessage||"Could not admit patient")}};
 const discharge=async id=>{try{await ipdApi.discharge(id);toast.success("Admission discharged");load()}catch(e){toast.error(e.friendlyMessage||"Could not discharge admission")}};
 if(loading)return <FullPageLoader label="Loading beds and admissions…"/>;
 return <div><PageHeader eyebrow="IPD" title="Beds & Admissions" subtitle="Manage wards, bed occupancy and active admissions."/>
 {user.role!=="PATIENT"&&<div className="grid sm:grid-cols-3 gap-4 mb-6"><StatCard label="Total beds" value={beds.length} icon="🛏️"/><StatCard label="Available" value={beds.filter(x=>x.status==="AVAILABLE").length} icon="✓" accent="clover"/><StatCard label="Occupied" value={beds.filter(x=>x.status==="OCCUPIED").length} icon="●" accent="clay"/></div>}
 {user.role!=="PATIENT"&&canBed&&<form onSubmit={addBed} className="card p-5 mb-6 grid md:grid-cols-3 gap-3"><input className="input" placeholder="Ward name" value={bf.wardName} onChange={e=>setBf({...bf,wardName:e.target.value})} required/><input className="input" placeholder="Bed number" value={bf.bedNumber} onChange={e=>setBf({...bf,bedNumber:e.target.value})} required/><button className="btn-primary">Add bed</button></form>}
 {user.role!=="PATIENT"&&canAdmit&&<form onSubmit={admit} className="card p-5 mb-6 grid md:grid-cols-3 gap-3"><input className="input" placeholder="Patient ID" value={af.patientId} onChange={e=>setAf({...af,patientId:e.target.value})} required/><select className="input" value={af.bedId} onChange={e=>setAf({...af,bedId:e.target.value})} required><option value="">Select available bed</option>{beds.filter(x=>x.status==="AVAILABLE").map(x=><option key={x.id} value={x.id}>{x.wardName} · {x.bedNumber}</option>)}</select><button className="btn-primary">Admit to bed</button></form>}
 {user.role==="PATIENT"?<div className="card overflow-x-auto"><h3 className="font-semibold p-4 border-b border-line">My admissions</h3><table className="w-full text-sm"><thead><tr><th className="th">ID</th><th className="th">Ward</th><th className="th">Bed</th><th className="th">Status</th><th className="th">Action</th></tr></thead><tbody>{beds.map(b=><tr className="border-t border-line" key={b.id}><td className="td">{b.id}</td><td className="td">{b.wardName}</td><td className="td">{b.bedNumber}</td><td className="td">{b.status}</td><td className="td">{canDeleteBed&&<button className="btn-danger px-2 py-1 text-xs" onClick={async()=>{try{await ipdApi.removeBed(b.id);load()}catch(e){toast.error(e.friendlyMessage||"Could not delete bed")}}}>Delete</button>}</td></tr>)}</tbody></table></div>
 <div className="card overflow-x-auto"><h3 className="font-semibold p-4 border-b border-line">Active admissions</h3><table className="w-full text-sm"><thead><tr><th className="th">ID</th><th className="th">Patient</th><th className="th">Ward</th><th className="th">Bed</th><th className="th">Action</th></tr></thead><tbody>{admissions.map(a=><tr className="border-t border-line" key={a.id}><td className="td">{a.id}</td><td className="td">{a.patientId}</td><td className="td">{a.wardName}</td><td className="td">{a.bedNumber}</td><td className="td">{canDischarge&&<button className="btn-outline px-2 py-1 text-xs" onClick={()=>discharge(a.id)}>Discharge</button>}</td></tr>)}</tbody></table>{!admissions.length&&<p className="p-4 text-sm text-ink-400">No active admissions.</p>}</div></div></div>
}