import {useEffect,useState} from "react";
import {stockApi} from "../../api/hmsModules"; import {useToast} from "../../context/ToastContext"; import {PageHeader,FullPageLoader,StatCard} from "../../components/Atoms";
const blank={medicineName:"",availableQuantity:0,rate:0};
export default function MedicineStock(){
 const toast=useToast(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [f,setF]=useState(blank); const [edit,setEdit]=useState(null);
 const load=async()=>{try{setRows(await stockApi.all()||[])}catch(e){toast.error(e.friendlyMessage||"Could not load medicine stock")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();try{const p={medicineName:f.medicineName,availableQuantity:Number(f.availableQuantity),rate:Number(f.rate)};if(edit)await stockApi.update(edit,p);else await stockApi.create(p);toast.success(edit?"Stock updated":"Medicine added");setF(blank);setEdit(null);load()}catch(e){toast.error(e.friendlyMessage||"Could not save stock")}};
 const qty=async(id,type)=>{const n=Number(window.prompt("Quantity", "1"));if(!n)return;try{if(type==="add")await stockApi.addQuantity(id,n);else await stockApi.reduceQuantity(id,n);toast.success("Quantity updated");load()}catch(e){toast.error(e.friendlyMessage||"Could not update quantity")}};
 const remove=async id=>{if(!window.confirm("Delete stock item?"))return;try{await stockApi.remove(id);toast.success("Stock deleted");load()}catch(e){toast.error(e.friendlyMessage||"Could not delete stock")}};
 if(loading)return <FullPageLoader label="Loading medicine stock…"/>;
 return <div><PageHeader eyebrow="Pharmacy" title="Medicine Stock" subtitle="Maintain quantities, rates and availability."/>
 <div className="grid sm:grid-cols-3 gap-4 mb-6"><StatCard label="Items" value={rows.length} icon="💊"/><StatCard label="Available" value={rows.filter(x=>x.available).length} icon="✓"/><StatCard label="Low / unavailable" value={rows.filter(x=>!x.available).length} icon="!" accent="clay"/></div>
 <form onSubmit={save} className="card p-5 mb-6 grid md:grid-cols-4 gap-3"><input className="input" placeholder="Medicine name" value={f.medicineName} onChange={e=>setF({...f,medicineName:e.target.value})} required/><input className="input" type="number" min="0" placeholder="Quantity" value={f.availableQuantity} onChange={e=>setF({...f,availableQuantity:e.target.value})} required/><input className="input" type="number" min="0" step="0.01" placeholder="Rate" value={f.rate} onChange={e=>setF({...f,rate:e.target.value})} required/><button className="btn-primary">{edit?"Update":"Add"} stock</button>{edit&&<button type="button" className="btn-outline" onClick={()=>{setEdit(null);setF(blank)}}>Cancel</button>}</form>
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="th">ID</th><th className="th">Medicine</th><th className="th">Qty</th><th className="th">Rate</th><th className="th">Available</th><th className="th">Actions</th></tr></thead><tbody>{rows.map(r=><tr className="border-t border-line" key={r.id}><td className="td">{r.id}</td><td className="td font-medium">{r.medicineName}</td><td className="td">{r.availableQuantity}</td><td className="td">₹{Number(r.rate||0).toFixed(2)}</td><td className="td">{r.available?"Yes":"No"}</td><td className="td"><div className="flex gap-2 flex-wrap"><button className="btn-outline px-2 py-1 text-xs" onClick={()=>{setEdit(r.id);setF({medicineName:r.medicineName||"",availableQuantity:r.availableQuantity||0,rate:r.rate||0})}}>Edit</button><button className="btn-outline px-2 py-1 text-xs" onClick={()=>qty(r.id,"add")}>+ Qty</button><button className="btn-outline px-2 py-1 text-xs" onClick={()=>qty(r.id,"reduce")}>− Qty</button><button className="btn-danger px-2 py-1 text-xs" onClick={()=>remove(r.id)}>Delete</button></div></td></tr>)}</tbody></table></div></div>
}