import {useEffect,useState} from "react";
import {departmentApi} from "../../api/hmsModules"; import {useToast} from "../../context/ToastContext"; import {PageHeader,FullPageLoader} from "../../components/Atoms";
const blank={name:"",description:"",active:true};
export default function Departments(){
 const toast=useToast(); const [rows,setRows]=useState([]); const [f,setF]=useState(blank); const [edit,setEdit]=useState(null); const [loading,setLoading]=useState(true);
 const load=async()=>{try{setRows(await departmentApi.all()||[])}catch(e){toast.error(e.friendlyMessage||"Could not load departments")}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();try{if(edit)await departmentApi.update(edit,f);else await departmentApi.create(f);toast.success(edit?"Department updated":"Department created");setF(blank);setEdit(null);load()}catch(e){toast.error(e.friendlyMessage||"Could not save department")}};
 const remove=async id=>{if(!window.confirm("Delete this department?"))return;try{await departmentApi.remove(id);toast.success("Department deleted");load()}catch(e){toast.error(e.friendlyMessage||"Could not delete department")}};
 if(loading)return <FullPageLoader label="Loading departments…"/>;
 return <div><PageHeader eyebrow="Admin" title="Departments" subtitle="Create departments and assign doctors to them."/>
 <form onSubmit={save} className="card p-5 mb-6 grid md:grid-cols-4 gap-3"><input className="input" placeholder="Department name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input className="input md:col-span-2" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.active} onChange={e=>setF({...f,active:e.target.checked})}/> Active</label><div className="md:col-span-4 flex gap-2"><button className="btn-primary">{edit?"Update":"Create"} department</button>{edit&&<button type="button" className="btn-outline" onClick={()=>{setEdit(null);setF(blank)}}>Cancel</button>}</div></form>
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="th">ID</th><th className="th">Name</th><th className="th">Description</th><th className="th">Active</th><th className="th">Action</th></tr></thead><tbody>{rows.map(r=><tr className="border-t border-line" key={r.id}><td className="td">{r.id}</td><td className="td font-medium">{r.name}</td><td className="td">{r.description||"—"}</td><td className="td">{r.active?"Yes":"No"}</td><td className="td flex gap-2"><button className="btn-outline px-2 py-1 text-xs" onClick={()=>{setEdit(r.id);setF({name:r.name||"",description:r.description||"",active:r.active!==false})}}>Edit</button><button className="btn-danger px-2 py-1 text-xs" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div></div>
}