package com.hospital.imp;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.hospital.Dto.*; import com.hospital.enums.AppointmentStatus; import com.hospital.model.*; import com.hospital.repository.*;
@Service public class AppointmentServiceImpl implements com.hospital.service.
AppointmentService{
 private final AppointmentRepository repo; private final PatientRepository patients;
 private final DocterRepository doctors; private final DoctorScheduleRepository schedules;
 private final DoctorLeaveRepository leaves;
 public AppointmentServiceImpl(AppointmentRepository repo,PatientRepository patients,
		 DocterRepository doctors,DoctorScheduleRepository schedules,DoctorLeaveRepository leaves){this.repo=repo;this.patients=patients;this.doctors=doctors;this.schedules=schedules;this.leaves=leaves;}
 @Transactional public AppointmentResponse create(AppointmentRequest r){validate(r); Patient p=patients.findById(r.getPatientId()).orElseThrow(()->new RuntimeException("Patient not found")); Doctor d=doctors.findById(r.getDoctorId()).orElseThrow(()->new RuntimeException("Doctor not found")); checkSlot(d,r.getAppointmentDate(),r.getTimeSlot()); Appointment a=Appointment.builder().patient(p).doctor(d).appointmentDate(r.getAppointmentDate()).timeSlot(r.getTimeSlot()).reason(r.getReason()).status(AppointmentStatus.PENDING).build();return map(repo.save(a));}
 public List<AppointmentResponse> all(){return repo.findAll().stream().sorted(Comparator.comparing(Appointment::getAppointmentDate).thenComparing(Appointment::getTimeSlot)).map(this::map).toList();}
 public AppointmentResponse get(Long id){return map(repo.findById(id).orElseThrow(()->new RuntimeException("Appointment not found")));}
 public AppointmentResponse update(Long id,AppointmentRequest r){Appointment a=repo.findById(id).orElseThrow(()->new RuntimeException("Appointment not found"));if(r.getAppointmentDate()!=null&&!r.getAppointmentDate().equals(a.getAppointmentDate())||r.getTimeSlot()!=null&&!r.getTimeSlot().equals(a.getTimeSlot())){checkSlot(a.getDoctor(),r.getAppointmentDate()==null?a.getAppointmentDate():r.getAppointmentDate(),r.getTimeSlot()==null?a.getTimeSlot():r.getTimeSlot());}if(r.getAppointmentDate()!=null)a.setAppointmentDate(r.getAppointmentDate());if(r.getTimeSlot()!=null)a.setTimeSlot(r.getTimeSlot());if(r.getReason()!=null)a.setReason(r.getReason());return map(repo.save(a));}
 public AppointmentResponse status(Long id,AppointmentStatus s){Appointment a=repo.findById(id).orElseThrow(()->new RuntimeException("Appointment not found"));a.setStatus(s);return map(repo.save(a));}
 public void cancel(Long id){status(id,AppointmentStatus.CANCELLED);}
 public List<AppointmentResponse> byDoctor(Long id){return repo.findByDoctorIdOrderByAppointmentDateAscTimeSlotAsc(id).stream().map(this::map).toList();}
 public List<AppointmentResponse> byPatient(Long id){return repo.findByPatientIdOrderByAppointmentDateDescTimeSlotDesc(id).stream().map(this::map).toList();}
 private void validate(AppointmentRequest r){if(r.getPatientId()==null||r.getDoctorId()==null||r.getAppointmentDate()==null||r.getTimeSlot()==null)throw new RuntimeException("Patient, doctor, date and time are required");if(r.getAppointmentDate().isBefore(java.time.LocalDate.now()))throw new RuntimeException("Appointment date cannot be in the past");}
 private void checkSlot(Doctor d,java.time.LocalDate date,java.time.LocalTime time){if(leaves.existsByDoctorIdAndLeaveDate(d.getId(),date))throw new RuntimeException("Doctor is on leave on this date");boolean valid=schedules.findByDoctorIdOrderByDayOfWeekAscStartTimeAsc(d.getId()).stream().anyMatch(s->s.isActive()&&s.getDayOfWeek()==date.getDayOfWeek()&&!time.isBefore(s.getStartTime())&&time.plusMinutes(s.getSlotMinutes()).compareTo(s.getEndTime())<=0);if(!valid)throw new RuntimeException("Selected time is outside doctor's available schedule");if(repo.existsByDoctorIdAndAppointmentDateAndTimeSlotAndStatusNot(d.getId(),date,time,AppointmentStatus.CANCELLED))throw new RuntimeException("Doctor slot already booked");}
 private AppointmentResponse map(Appointment a){return AppointmentResponse.builder().id(a.getId()).patientId(a.getPatient().getId()).doctorId(a.getDoctor().getId()).patientName(a.getPatient().getUser().getName()).doctorName(a.getDoctor().getUser().getName()).appointmentDate(a.getAppointmentDate()).timeSlot(a.getTimeSlot()).status(a.getStatus()).reason(a.getReason()).build();}
}
