package com.hospital.imp;
import java.io.*; import java.util.*;
import java.util.List;

import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.hospital.Dto.*; import com.hospital.enums.PaymentStatus; import com.hospital.model.*; import com.hospital.repository.*; import com.lowagie.text.*; import com.lowagie.text.pdf.*;
@Service public class BillingServiceImpl implements com.hospital.service.BillingService{
 private final BillRepository bills; private final PatientRepository patients; private final AppointmentRepository appointments;
 public BillingServiceImpl(BillRepository b,PatientRepository p,AppointmentRepository a){bills=b;patients=p;appointments=a;}
 @Transactional public BillResponse create(BillRequest r){Patient p=patients.findById(r.getPatientId()).orElseThrow(()->new RuntimeException("Patient not found"));Appointment a=r.getAppointmentId()==null?null:appointments.findById(r.getAppointmentId()).orElseThrow(()->new RuntimeException("Appointment not found"));if(r.getItems()==null||r.getItems().isEmpty())throw new RuntimeException("At least one bill item is required");Bill b=Bill.builder().patient(p).appointment(a).build();double total=0;for(BillItemRequest x:r.getItems()){if(x.getAmount()==null||x.getAmount()<0)throw new RuntimeException("Invalid bill amount");int q=x.getQuantity()==null||x.getQuantity()<1?1:x.getQuantity();double line=x.getAmount()*q;BillItem item=BillItem.builder().bill(b).itemType(x.getItemType()).description(x.getDescription()).amount(x.getAmount()).quantity(q).build();b.getItems().add(item);total+=line;}b.setTotalAmount(total);b.setPaidAmount(0.0);b.setStatus(total==0?PaymentStatus.PAID:PaymentStatus.PENDING);return map(bills.save(b));}
 public List<BillResponse> all1(PaymentStatus status,Long patientId){List<Bill> x=patientId!=null?bills.findByPatientIdOrderByCreatedAtDesc(patientId):(status!=null?bills.findByStatusOrderByCreatedAtDesc(status):bills.findAll());return x.stream().map(this::map).toList();}
 public BillResponse get(Long id){return map(bills.findById(id).orElseThrow(()->new RuntimeException("Bill not found")));}
 @Transactional public BillResponse pay(Long id,PaymentRequest r){Bill b=bills.findById(id).orElseThrow(()->new RuntimeException("Bill not found"));double amount=r.getAmount()==null?b.getTotalAmount()-b.getPaidAmount():r.getAmount();if(amount<=0)throw new RuntimeException("Payment amount must be greater than zero");if(amount>b.getTotalAmount()-b.getPaidAmount())throw new RuntimeException("Payment exceeds outstanding balance");b.setPaidAmount(b.getPaidAmount()+amount);b.setStatus(b.getPaidAmount()>=b.getTotalAmount()?PaymentStatus.PAID:PaymentStatus.PARTIALLY_PAID);return map(bills.save(b));}
 public byte[] invoice(Long id){Bill b=bills.findById(id).orElseThrow(()->new RuntimeException("Bill not found"));try(ByteArrayOutputStream out=new ByteArrayOutputStream()){Document doc=new Document(PageSize.A4);PdfWriter.getInstance(doc,out);doc.open();Font title=FontFactory.getFont(FontFactory.HELVETICA_BOLD,18);doc.add(new Paragraph("MERIDIAN CARE - HOSPITAL",title));doc.add(new Paragraph("Invoice / Receipt #"+b.getId()));doc.add(new Paragraph("Patient: "+b.getPatient().getUser().getName()+" | Patient ID: "+b.getPatient().getId()));doc.add(new Paragraph("Date: "+b.getCreatedAt()));doc.add(Chunk.NEWLINE);PdfPTable table=new PdfPTable(5);String[] h={"Type","Description","Qty","Rate","Amount"};for(String s:h)table.addCell(s);for(BillItem i:b.getItems()){table.addCell(i.getItemType().name());table.addCell(i.getDescription());table.addCell(String.valueOf(i.getQuantity()));table.addCell(String.format("%.2f",i.getAmount()));table.addCell(String.format("%.2f",i.getAmount()*i.getQuantity()));}doc.add(table);doc.add(Chunk.NEWLINE);doc.add(new Paragraph(String.format("Total: ₹ %.2f",b.getTotalAmount())));doc.add(new Paragraph(String.format("Paid: ₹ %.2f",b.getPaidAmount())));doc.add(new Paragraph(String.format("Balance: ₹ %.2f",b.getTotalAmount()-b.getPaidAmount())));doc.add(new Paragraph("Payment Status: "+b.getStatus()));doc.close();return out.toByteArray();}catch(Exception e){throw new RuntimeException("Unable to generate PDF invoice",e);}}
 private BillResponse map(Bill b){List<BillItemResponse> items=b.getItems().stream().map(i->BillItemResponse.builder().id(i.getId()).itemType(i.getItemType()).description(i.getDescription()).amount(i.getAmount()).quantity(i.getQuantity()).build()).toList();return BillResponse.builder().id(b.getId()).patientId(b.getPatient().getId()).appointmentId(b.getAppointment()==null?null:b.getAppointment().getId()).patientName(b.getPatient().getUser().getName()).totalAmount(b.getTotalAmount()).paidAmount(b.getPaidAmount()).balanceAmount(b.getTotalAmount()-b.getPaidAmount()).status(b.getStatus()).createdAt(b.getCreatedAt()).items(items).build();}
 @Override
 public List<BillResponse> all(PaymentStatus status, Long patientId) {
	// TODO Auto-generated method stub
	return null;
 }
}
