package com.hospital.imp;
import java.time.LocalDateTime; import java.util.*; import org.springframework.stereotype.Service; import com.hospital.Dto.*; import com.hospital.enums.LabTestStatus; import com.hospital.model.*; import com.hospital.repository.*;
@Service public class LabTestServiceImpl implements com.hospital.service.LabTestService{
 private final LabTestRepository repo;private final PatientRepository patients;private final DocterRepository doctors;private final MedicalRecordRepository records;
 public LabTestServiceImpl(LabTestRepository r,PatientRepository p,DocterRepository d,MedicalRecordRepository m){repo=r;patients=p;doctors=d;records=m;}
 public LabTestResponse create(LabTestRequest r){Patient p=patients.findById(r.getPatientId()).orElseThrow(()->new RuntimeException("Patient not found"));Doctor d=doctors.findById(r.getDoctorId()).orElseThrow(()->new RuntimeException("Doctor not found"));MedicalRecord m=r.getMedicalRecordId()==null?null:records.findById(r.getMedicalRecordId()).orElseThrow(()->new RuntimeException("Medical record not found"));if(r.getTestName()==null||r.getTestName().isBlank())throw new RuntimeException("Test name is required");return map(repo.save(LabTest.builder().patient(p).doctor(d).medicalRecord(m).testName(r.getTestName()).build()));}
 public List<LabTestResponse> byPatient(Long id){return repo.findByPatientIdOrderByRequestedAtDesc(id).stream().map(this::map).toList();} public List<LabTestResponse> all(){return repo.findAll().stream().map(this::map).toList();}
 public LabTestResponse result(Long id,LabTestResultRequest r){LabTest t=repo.findById(id).orElseThrow(()->new RuntimeException("Lab test not found"));t.setResultValue(r.getResultValue());t.setResultFileUrl(r.getResultFileUrl());t.setStatus(LabTestStatus.COMPLETED);t.setCompletedAt(LocalDateTime.now());return map(repo.save(t));}
 public LabTestResponse status(Long id,LabTestStatus s){LabTest t=repo.findById(id).orElseThrow(()->new RuntimeException("Lab test not found"));t.setStatus(s);if(s==LabTestStatus.COMPLETED)t.setCompletedAt(LocalDateTime.now());return map(repo.save(t));}
 private LabTestResponse map(LabTest t){return LabTestResponse.builder().id(t.getId()).patientId(t.getPatient().getId()).doctorId(t.getDoctor().getId()).medicalRecordId(t.getMedicalRecord()==null?null:t.getMedicalRecord().getId()).patientName(t.getPatient().getUser().getName()).doctorName(t.getDoctor().getUser().getName()).testName(t.getTestName()).status(t.getStatus()).resultValue(t.getResultValue()).resultFileUrl(t.getResultFileUrl()).requestedAt(t.getRequestedAt()).completedAt(t.getCompletedAt()).build();}
}
