package com.hospital.imp;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.hospital.Dto.*; import com.hospital.model.*; import com.hospital.repository.*;
@Service public class MedicalRecordServiceImpl implements com.hospital.service.MedicalRecordService{
 private final MedicalRecordRepository records; private final PrescriptionRepository prescriptions; private final PatientRepository patients; private final DocterRepository doctors; private final AppointmentRepository appointments;
 public MedicalRecordServiceImpl(MedicalRecordRepository r,PrescriptionRepository p,PatientRepository pa,DocterRepository d,AppointmentRepository a){records=r;prescriptions=p;patients=pa;doctors=d;appointments=a;}
 @Transactional public MedicalRecordResponse create(MedicalRecordRequest r){Patient p=patients.findById(r.getPatientId()).orElseThrow(()->new RuntimeException("Patient not found"));Doctor d=doctors.findById(r.getDoctorId()).orElseThrow(()->new RuntimeException("Doctor not found"));Appointment a=r.getAppointmentId()==null?null:appointments.findById(r.getAppointmentId()).orElseThrow(()->new RuntimeException("Appointment not found"));MedicalRecord m=MedicalRecord.builder().patient(p).doctor(d).appointment(a).diagnosis(r.getDiagnosis()).notes(r.getNotes()).build();return map(records.save(m));}
 public List<MedicalRecordResponse> byPatient(Long id){return records.findByPatientIdOrderByCreatedAtDesc(id).stream().map(this::map).toList();}
 public MedicalRecordResponse update(Long id,MedicalRecordRequest r){MedicalRecord m=records.findById(id).orElseThrow(()->new RuntimeException("Medical record not found"));if(r.getDiagnosis()!=null)m.setDiagnosis(r.getDiagnosis());if(r.getNotes()!=null)m.setNotes(r.getNotes());return map(records.save(m));}
 public PrescriptionResponse addPrescription(Long id,PrescriptionRequest r){MedicalRecord m=records.findById(id).orElseThrow(()->new RuntimeException("Medical record not found"));if(r.getMedicineName()==null||r.getMedicineName().isBlank())throw new RuntimeException("Medicine name is required");Prescription p=Prescription.builder().medicalRecord(m).medicineName(r.getMedicineName()).dosage(r.getDosage()).duration(r.getDuration()).instructions(r.getInstructions()).build();return pmap(prescriptions.save(p));}
 public List<PrescriptionResponse> prescriptions(Long id){return prescriptions.findByMedicalRecordId(id).stream().map(this::pmap).toList();}
 private MedicalRecordResponse map(MedicalRecord m){return MedicalRecordResponse.builder().id(m.getId()).patientId(m.getPatient().getId()).doctorId(m.getDoctor().getId()).appointmentId(m.getAppointment()==null?null:m.getAppointment().getId()).patientName(m.getPatient().getUser().getName()).doctorName(m.getDoctor().getUser().getName()).diagnosis(m.getDiagnosis()).notes(m.getNotes()).createdAt(m.getCreatedAt()).build();}
 private PrescriptionResponse pmap(Prescription p){return PrescriptionResponse.builder().id(p.getId()).medicalRecordId(p.getMedicalRecord().getId()).medicineName(p.getMedicineName()).dosage(p.getDosage()).duration(p.getDuration()).instructions(p.getInstructions()).build();}
}
